version: '3.8'
services:
  app:
    container_name: structura-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=https://shaikyakoub.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      
      # Storage
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - DO_SPACES_CDN=${DO_SPACES_CDN}

      # Email
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}

      # Auth (Google/GitHub)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}

    networks:
      - coolify

networks:
  coolify:
    external: true
