version: '3.8'
services:
  app:
    container_name: structura-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      # These use the variables you set in Coolify Dashboard
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=https://shaikyakoub.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NODE_ENV=production
