version: '3.8'
services:
  app:
    container_name: structura-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=https://shaikyakoub.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.structura-custom.rule=Host(`shaikyakoub.com`)"
      - "traefik.http.routers.structura-custom.entrypoints=websecure"
      - "traefik.http.routers.structura-custom.tls.certresolver=letsencrypt"
      - "traefik.http.services.structura-custom.loadbalancer.server.port=3000"
